// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRii5_6sl1frs9tpxbmGXv8erZ0EOrl9U',
    appId: '1:622702553258:web:746cb7372e26a9de0cc8d3',
    messagingSenderId: '622702553258',
    projectId: 'showbizapp-f8f9d',
    authDomain: 'showbizapp-f8f9d.firebaseapp.com',
    storageBucket: 'showbizapp-f8f9d.firebasestorage.app',
    measurementId: 'G-43PJHXKXK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYtrEBRLXIeTvRns604B2DT578dFmuzzA',
    appId: '1:622702553258:android:97e9ac7e405aac380cc8d3',
    messagingSenderId: '622702553258',
    projectId: 'showbizapp-f8f9d',
    storageBucket: 'showbizapp-f8f9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0R2HpcZNiA86woWgK97eWj6kvQA8kO4',
    appId: '1:622702553258:ios:7c80988f2b1a38dd0cc8d3',
    messagingSenderId: '622702553258',
    projectId: 'showbizapp-f8f9d',
    storageBucket: 'showbizapp-f8f9d.firebasestorage.app',
    iosBundleId: 'com.example.showbizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0R2HpcZNiA86woWgK97eWj6kvQA8kO4',
    appId: '1:622702553258:ios:7c80988f2b1a38dd0cc8d3',
    messagingSenderId: '622702553258',
    projectId: 'showbizapp-f8f9d',
    storageBucket: 'showbizapp-f8f9d.firebasestorage.app',
    iosBundleId: 'com.example.showbizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRii5_6sl1frs9tpxbmGXv8erZ0EOrl9U',
    appId: '1:622702553258:web:69b37a782006c4000cc8d3',
    messagingSenderId: '622702553258',
    projectId: 'showbizapp-f8f9d',
    authDomain: 'showbizapp-f8f9d.firebaseapp.com',
    storageBucket: 'showbizapp-f8f9d.firebasestorage.app',
    measurementId: 'G-5HGSX9GEMY',
  );
}
